services:
  frontend:
    build: .
    container_name: rently-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=https://sse-backend-1e76.onrender.com

